spring:
  application:
    name: backend
  servlet:
    multipart:
      max-file-size: 1MB
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:/db/changelog/app-changelog.xml
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      port: ${REDIS_PORT}
  session:
    redis:
      flush-mode: on_save
      namespace: ${REDIS_SESSION_NAMESPACE}
    timeout: ${REDIS_SESSION_TIMEOUT}
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        region: ${AWS_S3_REGION}

s3:
  bucket:
    name: ${BUCKET_NAME}

jwt:
  email:
    secret: ${JWT_EMAIL_SECRET}

client:
  base-url: ${CLIENT_BASE_URL}


