/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as IndexImport } from './routes/index'
import { Route as SelectWorkspaceIndexImport } from './routes/select-workspace/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as WorkspacesWorkspaceIdImport } from './routes/workspaces/$workspaceId'
import { Route as VerifyEmailTokenImport } from './routes/verify-email.$token'
import { Route as AuthLayoutImport } from './routes/auth/_layout'
import { Route as WorkspacesWorkspaceIdIndexImport } from './routes/workspaces/$workspaceId.index'
import { Route as WorkspacesWorkspaceIdSettingsImport } from './routes/workspaces/$workspaceId.settings'
import { Route as WorkspacesWorkspaceIdActivityImport } from './routes/workspaces/$workspaceId.activity'
import { Route as AuthLayoutRegisterImport } from './routes/auth/_layout.register'
import { Route as AuthLayoutLoginImport } from './routes/auth/_layout.login'
import { Route as WorkspacesWorkspaceIdSettingsIndexImport } from './routes/workspaces/$workspaceId.settings.index'
import { Route as WorkspacesWorkspaceIdSettingsWorkspaceSettingsImport } from './routes/workspaces/$workspaceId.settings.workspace-settings'

// Create Virtual Routes

const AuthImport = createFileRoute('/auth')()

// Create/Update Routes

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SelectWorkspaceIndexRoute = SelectWorkspaceIndexImport.update({
  path: '/select-workspace/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdImport.update({
  path: '/workspaces/$workspaceId',
  getParentRoute: () => rootRoute,
} as any)

const VerifyEmailTokenRoute = VerifyEmailTokenImport.update({
  path: '/verify-email/$token',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRoute,
} as any)

const WorkspacesWorkspaceIdIndexRoute = WorkspacesWorkspaceIdIndexImport.update(
  {
    path: '/',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any,
)

const WorkspacesWorkspaceIdSettingsRoute =
  WorkspacesWorkspaceIdSettingsImport.update({
    path: '/settings',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)

const WorkspacesWorkspaceIdActivityRoute =
  WorkspacesWorkspaceIdActivityImport.update({
    path: '/activity',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)

const AuthLayoutRegisterRoute = AuthLayoutRegisterImport.update({
  path: '/register',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutLoginRoute = AuthLayoutLoginImport.update({
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const WorkspacesWorkspaceIdSettingsIndexRoute =
  WorkspacesWorkspaceIdSettingsIndexImport.update({
    path: '/',
    getParentRoute: () => WorkspacesWorkspaceIdSettingsRoute,
  } as any)

const WorkspacesWorkspaceIdSettingsWorkspaceSettingsRoute =
  WorkspacesWorkspaceIdSettingsWorkspaceSettingsImport.update({
    path: '/workspace-settings',
    getParentRoute: () => WorkspacesWorkspaceIdSettingsRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/auth/_layout': {
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof AuthRoute
    }
    '/verify-email/$token': {
      preLoaderRoute: typeof VerifyEmailTokenImport
      parentRoute: typeof rootRoute
    }
    '/workspaces/$workspaceId': {
      preLoaderRoute: typeof WorkspacesWorkspaceIdImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/select-workspace/': {
      preLoaderRoute: typeof SelectWorkspaceIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/_layout/login': {
      preLoaderRoute: typeof AuthLayoutLoginImport
      parentRoute: typeof AuthLayoutImport
    }
    '/auth/_layout/register': {
      preLoaderRoute: typeof AuthLayoutRegisterImport
      parentRoute: typeof AuthLayoutImport
    }
    '/workspaces/$workspaceId/activity': {
      preLoaderRoute: typeof WorkspacesWorkspaceIdActivityImport
      parentRoute: typeof WorkspacesWorkspaceIdImport
    }
    '/workspaces/$workspaceId/settings': {
      preLoaderRoute: typeof WorkspacesWorkspaceIdSettingsImport
      parentRoute: typeof WorkspacesWorkspaceIdImport
    }
    '/workspaces/$workspaceId/': {
      preLoaderRoute: typeof WorkspacesWorkspaceIdIndexImport
      parentRoute: typeof WorkspacesWorkspaceIdImport
    }
    '/workspaces/$workspaceId/settings/workspace-settings': {
      preLoaderRoute: typeof WorkspacesWorkspaceIdSettingsWorkspaceSettingsImport
      parentRoute: typeof WorkspacesWorkspaceIdSettingsImport
    }
    '/workspaces/$workspaceId/settings/': {
      preLoaderRoute: typeof WorkspacesWorkspaceIdSettingsIndexImport
      parentRoute: typeof WorkspacesWorkspaceIdSettingsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRoute.addChildren([
    AuthLayoutRoute.addChildren([
      AuthLayoutLoginRoute,
      AuthLayoutRegisterRoute,
    ]),
    AuthIndexRoute,
  ]),
  VerifyEmailTokenRoute,
  WorkspacesWorkspaceIdRoute.addChildren([
    WorkspacesWorkspaceIdActivityRoute,
    WorkspacesWorkspaceIdSettingsRoute.addChildren([
      WorkspacesWorkspaceIdSettingsWorkspaceSettingsRoute,
      WorkspacesWorkspaceIdSettingsIndexRoute,
    ]),
    WorkspacesWorkspaceIdIndexRoute,
  ]),
  SelectWorkspaceIndexRoute,
])

/* prettier-ignore-end */
