spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/obiflow
    username: postgres
    password: postgres
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  data:
    redis:
      host: localhost
      password: ""
      port: 6379
  session:
    redis:
      namespace: quirely:session
    timeout: 2592000s

s3:
  bucket:
    name: quirely

jwt:
  email:
    secret: 9EgpNuxBG7DveSj3GpvfauJVQiOhV1RM

client:
  base-url: http://localhost:5173


